spring:
  r2dbc:
    url: r2dbc:postgres://localhost:5432/dev_db
    username: dev
    password: devpassword
  sql:
    init:
      schema-locations:
        - classpath:db/schema/schema.sql
services:
  users: localhost:15001
  accessManager: localhost:15003